version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pdf_insighter_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  features:
    build:
      context: ./Features
      dockerfile: Dockerfile
    container_name: pdf_insighter_features
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      # This 'args' section is required to pass the key during the build
      args:
        - ADOBE_EMBED_API_KEY=${VITE_ADOBE_CLIENT_ID_LH} # Corrected to use the localhost key
    container_name: pdf_insighter_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - features
    restart: unless-stopped
